{% set name = "dropbox" %}
{% set version = "11.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dropbox/dropbox-sdk-python/archive/v{{ version }}.tar.gz
  sha256: 5db4f1bcece589f5f3f6cd6c5f8e0950f06e97384fa3cc2be127f86f698c07dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ==5.2.0
    - python =2.7|>=3.4
  run:
    - ply
    - pytest
    - pytest-runner
    - python =2.7|>=3.4
    - requests
    - six ==1.14.0
    - stone >=2
    - sphinx
    - twine
    - wheel

test:
  imports:
    - dropbox
  commands:
    - pip check
    - pytest test/unit/test_dropbox_unit.py
  requires:
    - pip
    - mock
    - pytest-mock
    - coverage
  source_files:
    - test

about:
  home: http://www.dropbox.com/developers
  summary: Official Dropbox API Client
  description: The Official Dropbox API V2 SDK for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/dropbox-sdk-python
  doc_url: https://dropbox-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - guillochon
    - BastianZim
