{% set name = "dropbox" %}
{% set version = "11.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dropbox/dropbox-sdk-python/archive/v{{ version }}.tar.gz
  sha256: c3b961649080525e52b4c43ca751fb8a6b7d8d7cfd661eaca8588d9c2a4d6aa3

build:
  number: 0
  skip: True  # [win]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ==5.2.0
    - python =2.7|>=3.4
  run:
    - python =2.7|>=3.4
    - requests >=2.16.2
    - six >=1.12.0
    - stone >=2

test:
  imports:
    - dropbox
  commands:
    - pip check
    - pytest test/unit/test_dropbox_unit.py
  requires:
    - pip
    - mock
    - pytest-mock
    - coverage
  source_files:
    - test

about:
  home: http://www.dropbox.com/developers
  summary: Official Dropbox API Client
  description: The Official Dropbox API V2 SDK for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/dropbox-sdk-python
  doc_url: https://dropbox-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - guillochon
    - BastianZim