{% set version = "9.2.0" %}

package:
  name: dropbox
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dropbox/dropbox-{{ version }}.tar.gz
  sha256: ecf024cde6e82b2fbc9fea6da20c3dc717ab7b68c903ec4fdd241b6728b13c88

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - setuptools
    - requests >=2.16.2
    - six >=1.3.0

test:
  imports:
    - dropbox

about:
  home: https://github.com/dropbox/dropbox-sdk-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Official Dropbox API Client'
  dev_url: https://github.com/dropbox/dropbox-sdk-python
  doc_url: https://dropbox-sdk-python.readthedocs.io/en/latest/

  description: |
    dropbox is a Python SDK for integrating with the Dropbox API v2.
    Compatible with Python 2.7 and 3.4+. Documentation is available on
    Read the Docs.

extra:
  recipe-maintainers:
    - guillochon
